// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRecentDeniedByUser = `-- name: CountRecentDeniedByUser :one
SELECT COUNT(*) FROM audit_events
WHERE user_id     = $1
  AND outcome     IN ('denied', 'rate_limited')
  AND occurred_at >= now() - ($2::text)::interval
`

type CountRecentDeniedByUserParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 string      `json:"column_2"`
}

// Used by the alerting worker to detect suspicious activity patterns.
func (q *Queries) CountRecentDeniedByUser(ctx context.Context, arg CountRecentDeniedByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentDeniedByUser, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    user_id,
    downstream_server_id,
    tool_name,
    input_params_redacted,
    outcome,
    response_summary,
    latency_ms
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, downstream_server_id, tool_name, input_params_redacted, outcome, response_summary, latency_ms, occurred_at
`

type CreateAuditEventParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	DownstreamServerID  pgtype.UUID `json:"downstream_server_id"`
	ToolName            string      `json:"tool_name"`
	InputParamsRedacted []byte      `json:"input_params_redacted"`
	Outcome             string      `json:"outcome"`
	ResponseSummary     []byte      `json:"response_summary"`
	LatencyMs           *int32      `json:"latency_ms"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.UserID,
		arg.DownstreamServerID,
		arg.ToolName,
		arg.InputParamsRedacted,
		arg.Outcome,
		arg.ResponseSummary,
		arg.LatencyMs,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DownstreamServerID,
		&i.ToolName,
		&i.InputParamsRedacted,
		&i.Outcome,
		&i.ResponseSummary,
		&i.LatencyMs,
		&i.OccurredAt,
	)
	return i, err
}

const getAuditEvent = `-- name: GetAuditEvent :one
SELECT id, user_id, downstream_server_id, tool_name, input_params_redacted, outcome, response_summary, latency_ms, occurred_at FROM audit_events
WHERE id = $1
`

func (q *Queries) GetAuditEvent(ctx context.Context, id pgtype.UUID) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, getAuditEvent, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DownstreamServerID,
		&i.ToolName,
		&i.InputParamsRedacted,
		&i.Outcome,
		&i.ResponseSummary,
		&i.LatencyMs,
		&i.OccurredAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, user_id, downstream_server_id, tool_name, input_params_redacted, outcome, response_summary, latency_ms, occurred_at FROM audit_events
ORDER BY occurred_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Paginated, most-recent first. Filtering is handled at the application layer.
func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DownstreamServerID,
			&i.ToolName,
			&i.InputParamsRedacted,
			&i.Outcome,
			&i.ResponseSummary,
			&i.LatencyMs,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByOutcome = `-- name: ListAuditEventsByOutcome :many
SELECT id, user_id, downstream_server_id, tool_name, input_params_redacted, outcome, response_summary, latency_ms, occurred_at FROM audit_events
WHERE outcome = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsByOutcomeParams struct {
	Outcome string `json:"outcome"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListAuditEventsByOutcome(ctx context.Context, arg ListAuditEventsByOutcomeParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByOutcome, arg.Outcome, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DownstreamServerID,
			&i.ToolName,
			&i.InputParamsRedacted,
			&i.Outcome,
			&i.ResponseSummary,
			&i.LatencyMs,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByServer = `-- name: ListAuditEventsByServer :many
SELECT id, user_id, downstream_server_id, tool_name, input_params_redacted, outcome, response_summary, latency_ms, occurred_at FROM audit_events
WHERE downstream_server_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsByServerParams struct {
	DownstreamServerID pgtype.UUID `json:"downstream_server_id"`
	Limit              int32       `json:"limit"`
	Offset             int32       `json:"offset"`
}

func (q *Queries) ListAuditEventsByServer(ctx context.Context, arg ListAuditEventsByServerParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByServer, arg.DownstreamServerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DownstreamServerID,
			&i.ToolName,
			&i.InputParamsRedacted,
			&i.Outcome,
			&i.ResponseSummary,
			&i.LatencyMs,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEventsByUser = `-- name: ListAuditEventsByUser :many
SELECT id, user_id, downstream_server_id, tool_name, input_params_redacted, outcome, response_summary, latency_ms, occurred_at FROM audit_events
WHERE user_id = $1
ORDER BY occurred_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditEventsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListAuditEventsByUser(ctx context.Context, arg ListAuditEventsByUserParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DownstreamServerID,
			&i.ToolName,
			&i.InputParamsRedacted,
			&i.Outcome,
			&i.ResponseSummary,
			&i.LatencyMs,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
