// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downstream_servers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDownstreamServer = `-- name: CreateDownstreamServer :one
INSERT INTO downstream_servers (name, base_url, auth_type, auth_secret_ref, tool_manifest)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, base_url, auth_type, auth_secret_ref, tool_manifest, is_active, created_at
`

type CreateDownstreamServerParams struct {
	Name          string `json:"name"`
	BaseUrl       string `json:"base_url"`
	AuthType      string `json:"auth_type"`
	AuthSecretRef string `json:"auth_secret_ref"`
	ToolManifest  []byte `json:"tool_manifest"`
}

func (q *Queries) CreateDownstreamServer(ctx context.Context, arg CreateDownstreamServerParams) (DownstreamServer, error) {
	row := q.db.QueryRow(ctx, createDownstreamServer,
		arg.Name,
		arg.BaseUrl,
		arg.AuthType,
		arg.AuthSecretRef,
		arg.ToolManifest,
	)
	var i DownstreamServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthType,
		&i.AuthSecretRef,
		&i.ToolManifest,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getDownstreamServer = `-- name: GetDownstreamServer :one
SELECT id, name, base_url, auth_type, auth_secret_ref, tool_manifest, is_active, created_at FROM downstream_servers
WHERE id = $1
`

func (q *Queries) GetDownstreamServer(ctx context.Context, id pgtype.UUID) (DownstreamServer, error) {
	row := q.db.QueryRow(ctx, getDownstreamServer, id)
	var i DownstreamServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthType,
		&i.AuthSecretRef,
		&i.ToolManifest,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getDownstreamServerByName = `-- name: GetDownstreamServerByName :one
SELECT id, name, base_url, auth_type, auth_secret_ref, tool_manifest, is_active, created_at FROM downstream_servers
WHERE name = $1
`

func (q *Queries) GetDownstreamServerByName(ctx context.Context, name string) (DownstreamServer, error) {
	row := q.db.QueryRow(ctx, getDownstreamServerByName, name)
	var i DownstreamServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthType,
		&i.AuthSecretRef,
		&i.ToolManifest,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveDownstreamServers = `-- name: ListActiveDownstreamServers :many
SELECT id, name, base_url, auth_type, auth_secret_ref, tool_manifest, is_active, created_at FROM downstream_servers
WHERE is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListActiveDownstreamServers(ctx context.Context) ([]DownstreamServer, error) {
	rows, err := q.db.Query(ctx, listActiveDownstreamServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownstreamServer{}
	for rows.Next() {
		var i DownstreamServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.AuthType,
			&i.AuthSecretRef,
			&i.ToolManifest,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownstreamServers = `-- name: ListDownstreamServers :many
SELECT id, name, base_url, auth_type, auth_secret_ref, tool_manifest, is_active, created_at FROM downstream_servers
ORDER BY name ASC
`

func (q *Queries) ListDownstreamServers(ctx context.Context) ([]DownstreamServer, error) {
	rows, err := q.db.Query(ctx, listDownstreamServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DownstreamServer{}
	for rows.Next() {
		var i DownstreamServer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.AuthType,
			&i.AuthSecretRef,
			&i.ToolManifest,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDownstreamServerActive = `-- name: SetDownstreamServerActive :one
UPDATE downstream_servers
SET is_active = $2
WHERE id = $1
RETURNING id, name, base_url, auth_type, auth_secret_ref, tool_manifest, is_active, created_at
`

type SetDownstreamServerActiveParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) SetDownstreamServerActive(ctx context.Context, arg SetDownstreamServerActiveParams) (DownstreamServer, error) {
	row := q.db.QueryRow(ctx, setDownstreamServerActive, arg.ID, arg.IsActive)
	var i DownstreamServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthType,
		&i.AuthSecretRef,
		&i.ToolManifest,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateDownstreamServer = `-- name: UpdateDownstreamServer :one
UPDATE downstream_servers
SET name            = $2,
    base_url        = $3,
    auth_type       = $4,
    auth_secret_ref = $5
WHERE id = $1
RETURNING id, name, base_url, auth_type, auth_secret_ref, tool_manifest, is_active, created_at
`

type UpdateDownstreamServerParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	BaseUrl       string      `json:"base_url"`
	AuthType      string      `json:"auth_type"`
	AuthSecretRef string      `json:"auth_secret_ref"`
}

func (q *Queries) UpdateDownstreamServer(ctx context.Context, arg UpdateDownstreamServerParams) (DownstreamServer, error) {
	row := q.db.QueryRow(ctx, updateDownstreamServer,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.AuthType,
		arg.AuthSecretRef,
	)
	var i DownstreamServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthType,
		&i.AuthSecretRef,
		&i.ToolManifest,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateToolManifest = `-- name: UpdateToolManifest :one
UPDATE downstream_servers
SET tool_manifest = $2
WHERE id = $1
RETURNING id, name, base_url, auth_type, auth_secret_ref, tool_manifest, is_active, created_at
`

type UpdateToolManifestParams struct {
	ID           pgtype.UUID `json:"id"`
	ToolManifest []byte      `json:"tool_manifest"`
}

func (q *Queries) UpdateToolManifest(ctx context.Context, arg UpdateToolManifestParams) (DownstreamServer, error) {
	row := q.db.QueryRow(ctx, updateToolManifest, arg.ID, arg.ToolManifest)
	var i DownstreamServer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.AuthType,
		&i.AuthSecretRef,
		&i.ToolManifest,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
