// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	DownstreamServerID  pgtype.UUID        `json:"downstream_server_id"`
	ToolName            string             `json:"tool_name"`
	InputParamsRedacted []byte             `json:"input_params_redacted"`
	Outcome             string             `json:"outcome"`
	ResponseSummary     []byte             `json:"response_summary"`
	LatencyMs           *int32             `json:"latency_ms"`
	OccurredAt          pgtype.Timestamptz `json:"occurred_at"`
}

type DownstreamServer struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	BaseUrl       string             `json:"base_url"`
	AuthType      string             `json:"auth_type"`
	AuthSecretRef string             `json:"auth_secret_ref"`
	ToolManifest  []byte             `json:"tool_manifest"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Policy struct {
	ID                 pgtype.UUID        `json:"id"`
	RoleID             pgtype.UUID        `json:"role_id"`
	DownstreamServerID pgtype.UUID        `json:"downstream_server_id"`
	ToolName           string             `json:"tool_name"`
	IsAllowed          bool               `json:"is_allowed"`
	RedactFields       []string           `json:"redact_fields"`
	MaxCallsPerMinute  int32              `json:"max_calls_per_minute"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	RoleID      pgtype.UUID        `json:"role_id"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
