// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePoliciesByRole = `-- name: DeletePoliciesByRole :exec
DELETE FROM policies
WHERE role_id = $1
`

func (q *Queries) DeletePoliciesByRole(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePoliciesByRole, roleID)
	return err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies
WHERE id = $1
`

func (q *Queries) DeletePolicy(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicy, id)
	return err
}

const getPolicy = `-- name: GetPolicy :one
SELECT id, role_id, downstream_server_id, tool_name, is_allowed, redact_fields, max_calls_per_minute, created_at FROM policies
WHERE id = $1
`

func (q *Queries) GetPolicy(ctx context.Context, id pgtype.UUID) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicy, id)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.DownstreamServerID,
		&i.ToolName,
		&i.IsAllowed,
		&i.RedactFields,
		&i.MaxCallsPerMinute,
		&i.CreatedAt,
	)
	return i, err
}

const getPolicyByRoleServerTool = `-- name: GetPolicyByRoleServerTool :one
SELECT id, role_id, downstream_server_id, tool_name, is_allowed, redact_fields, max_calls_per_minute, created_at FROM policies
WHERE role_id              = $1
  AND downstream_server_id = $2
  AND tool_name            = $3
`

type GetPolicyByRoleServerToolParams struct {
	RoleID             pgtype.UUID `json:"role_id"`
	DownstreamServerID pgtype.UUID `json:"downstream_server_id"`
	ToolName           string      `json:"tool_name"`
}

// Hot path — called by the policy engine on every proxied request.
func (q *Queries) GetPolicyByRoleServerTool(ctx context.Context, arg GetPolicyByRoleServerToolParams) (Policy, error) {
	row := q.db.QueryRow(ctx, getPolicyByRoleServerTool, arg.RoleID, arg.DownstreamServerID, arg.ToolName)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.DownstreamServerID,
		&i.ToolName,
		&i.IsAllowed,
		&i.RedactFields,
		&i.MaxCallsPerMinute,
		&i.CreatedAt,
	)
	return i, err
}

const listPoliciesByRole = `-- name: ListPoliciesByRole :many
SELECT id, role_id, downstream_server_id, tool_name, is_allowed, redact_fields, max_calls_per_minute, created_at FROM policies
WHERE role_id = $1
ORDER BY downstream_server_id, tool_name
`

func (q *Queries) ListPoliciesByRole(ctx context.Context, roleID pgtype.UUID) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.DownstreamServerID,
			&i.ToolName,
			&i.IsAllowed,
			&i.RedactFields,
			&i.MaxCallsPerMinute,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesByRoleAndServer = `-- name: ListPoliciesByRoleAndServer :many
SELECT id, role_id, downstream_server_id, tool_name, is_allowed, redact_fields, max_calls_per_minute, created_at FROM policies
WHERE role_id              = $1
  AND downstream_server_id = $2
ORDER BY tool_name
`

type ListPoliciesByRoleAndServerParams struct {
	RoleID             pgtype.UUID `json:"role_id"`
	DownstreamServerID pgtype.UUID `json:"downstream_server_id"`
}

func (q *Queries) ListPoliciesByRoleAndServer(ctx context.Context, arg ListPoliciesByRoleAndServerParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPoliciesByRoleAndServer, arg.RoleID, arg.DownstreamServerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Policy{}
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.DownstreamServerID,
			&i.ToolName,
			&i.IsAllowed,
			&i.RedactFields,
			&i.MaxCallsPerMinute,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPolicy = `-- name: UpsertPolicy :one
INSERT INTO policies (role_id, downstream_server_id, tool_name, is_allowed, redact_fields, max_calls_per_minute)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (role_id, downstream_server_id, tool_name) DO UPDATE
    SET is_allowed           = EXCLUDED.is_allowed,
        redact_fields        = EXCLUDED.redact_fields,
        max_calls_per_minute = EXCLUDED.max_calls_per_minute
RETURNING id, role_id, downstream_server_id, tool_name, is_allowed, redact_fields, max_calls_per_minute, created_at
`

type UpsertPolicyParams struct {
	RoleID             pgtype.UUID `json:"role_id"`
	DownstreamServerID pgtype.UUID `json:"downstream_server_id"`
	ToolName           string      `json:"tool_name"`
	IsAllowed          bool        `json:"is_allowed"`
	RedactFields       []string    `json:"redact_fields"`
	MaxCallsPerMinute  int32       `json:"max_calls_per_minute"`
}

// Used by the admin API to create or update a policy in one call.
func (q *Queries) UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, upsertPolicy,
		arg.RoleID,
		arg.DownstreamServerID,
		arg.ToolName,
		arg.IsAllowed,
		arg.RedactFields,
		arg.MaxCallsPerMinute,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.DownstreamServerID,
		&i.ToolName,
		&i.IsAllowed,
		&i.RedactFields,
		&i.MaxCallsPerMinute,
		&i.CreatedAt,
	)
	return i, err
}
