// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Used by the alerting worker to detect suspicious activity patterns.
	CountRecentDeniedByUser(ctx context.Context, arg CountRecentDeniedByUserParams) (int64, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvent, error)
	CreateDownstreamServer(ctx context.Context, arg CreateDownstreamServerParams) (DownstreamServer, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePoliciesByRole(ctx context.Context, roleID pgtype.UUID) error
	DeletePolicy(ctx context.Context, id pgtype.UUID) error
	DeleteRole(ctx context.Context, id pgtype.UUID) error
	GetAuditEvent(ctx context.Context, id pgtype.UUID) (AuditEvent, error)
	GetDownstreamServer(ctx context.Context, id pgtype.UUID) (DownstreamServer, error)
	GetDownstreamServerByName(ctx context.Context, name string) (DownstreamServer, error)
	GetPolicy(ctx context.Context, id pgtype.UUID) (Policy, error)
	// Hot path — called by the policy engine on every proxied request.
	GetPolicyByRoleServerTool(ctx context.Context, arg GetPolicyByRoleServerToolParams) (Policy, error)
	GetRole(ctx context.Context, id pgtype.UUID) (Role, error)
	GetRoleByName(ctx context.Context, name string) (Role, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListActiveDownstreamServers(ctx context.Context) ([]DownstreamServer, error)
	ListActiveUsers(ctx context.Context) ([]User, error)
	// Paginated, most-recent first. Filtering is handled at the application layer.
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error)
	ListAuditEventsByOutcome(ctx context.Context, arg ListAuditEventsByOutcomeParams) ([]AuditEvent, error)
	ListAuditEventsByServer(ctx context.Context, arg ListAuditEventsByServerParams) ([]AuditEvent, error)
	ListAuditEventsByUser(ctx context.Context, arg ListAuditEventsByUserParams) ([]AuditEvent, error)
	ListDownstreamServers(ctx context.Context) ([]DownstreamServer, error)
	ListPoliciesByRole(ctx context.Context, roleID pgtype.UUID) ([]Policy, error)
	ListPoliciesByRoleAndServer(ctx context.Context, arg ListPoliciesByRoleAndServerParams) ([]Policy, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SetDownstreamServerActive(ctx context.Context, arg SetDownstreamServerActiveParams) (DownstreamServer, error)
	SetUserActive(ctx context.Context, arg SetUserActiveParams) (User, error)
	UpdateDownstreamServer(ctx context.Context, arg UpdateDownstreamServerParams) (DownstreamServer, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateToolManifest(ctx context.Context, arg UpdateToolManifestParams) (DownstreamServer, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	// Used by the admin API to create or update a policy in one call.
	UpsertPolicy(ctx context.Context, arg UpsertPolicyParams) (Policy, error)
}

var _ Querier = (*Queries)(nil)
